version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./api/doc.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
